### ISSUE TITLE
RX data lost on Linux platfroms

### ISSUE THREAD

**Issue by kskog** [jcurl/RJCP.DLL.SerialPortStream#127] opened 2021-10-11 07:50 UTC
We sporadically lose a few bytes (RX) when runing on Linux platforms (custom Yocto build and Alpine arm64). This happens a few times a day and the nature/pattern of the lost data is the same each time.

I see that an issue maybe related to this have been fixed in commit a2464e1f04ef0d965b85ddfe78eba90b91cb95e3. We're currently running a test based on the v2.x branch to see if this fixes it.

@jcurl Latest release is from April, it would be great if you could build a new NuGet package release with the latest fixes. At least, a patch release is needed with the most important bugfixes.

**Comment by kskog** [comment] 2021-10-12 07:00
We get no data loss using the latest commit of v2.x :-) Could you please publish a prerelease build?

**Comment by kskog** [comment] 2021-10-12 13:03
oops.. was a bit too quick. Got an error event, so it's not fully fixed.

**Comment by kskog** [comment] 2021-10-12 15:05
Could you make a prerelase build based on one of the latest commits?

**Comment by jcurl** [comment] 2021-10-29 20:49
I'm wondering if you've had time to provide more detailed information regarding your problem. There are a couple of things you can do:
1. I've written a bpftrace program that can be run to monitor the serial port in question. The output can be traced and logged. It's written to work with bpftrace 0.9.4 (if you use a newer version, the `buf` function can be used to trace the contents of the read/write buffers also). I've attached it as a .zip file and I'm considering adding this to the repository.
2. Instrument the library libnserial to dump each call for `serial_read`, `serial_write`, `serial_waitforevent`, `serial_abortwaitforevent`, where extra information can be debugged. There's a `#define` in libnserial to enable logging (see the build.sh script that's present there).

[serial.bt.zip](https://github.com/jcurl/RJCP.DLL.SerialPortStream/files/7444824/serial.bt.zip)

As this is an open source project done in my spare time, I don't have the resources to debug various systems, and would very much appreciate your help in resolving this issue.

Regards - Jason.

**Comment by kskog** [comment] 2021-11-03 10:13
We have been struggling with other issues on the device, so I have not had the time to dig into this, but I will update here immediately when I have the opportunity.

**Comment by jcurl** [comment] 2021-12-31 20:06
Closing this issue, as there has been no activity or updates to identify the root cause. Please see the new release 2.4.0 which may contain potential fixes.

**Closed by jcurl** 2021-12-31 20:06 UTC
Labels: feedback-required
